[package]
name = "rusty_mars"
version = "0.1.0"
authors = ["Bob Chatman <bob.chatman@gmail.com>"]
publish = false

[[bin]]
name = "rusty_mars"
path = "src/main.rs"

[dependencies]
human_format = "1.0.0"
